### PR TITLE
Improve TreeView and Export performance

### PR DESCRIPTION
**Pull request by GICodeWarrior**
`Yield` gives other threads an explicit opportunity to run (i.e. to process input), without causing a fixed time penalty like `Sleep`.

This change improves export speed.

### CODE REVIEW

**Comment by 4sval** [comment]
It looks like this change has undesired effects where the thread worker is considered ready but has not finished his work. You can see this when expanding/collapsing folders.

Does this actually change the export speed or make it look like it changed the export speed? I couldn't find any significant improvement on my end.

**Comment by GICodeWarrior** [comment]
Ah, I see what you mean about the Expand All / Collapse All status not working. 🤔

Yes, for me it does speed up both the export and the expand/collapse.

I have a larger speed improvement for export in progress (a speed up for the console).  With that improvement, this change is much more apparent.  I thought I'd submit this while I clean up the other, since this is a smaller change.

I'll take a look at the status issue.

**Comment by GICodeWarrior** [comment]
At a glance, it seems the worker is actually finished that quickly.

Setting `IsExpanded` is a relatively fast operation.  It's the UI thread acting on that change that is taking actual time.

image

Given that expanding / collapsing the tree is purely a visual change, I wonder if it would be reasonable and more efficient to operate on the TreeView directly, rather than going through the overhead of the ViewModel.

**Comment by GICodeWarrior** [comment]
Ah, actually most of the cost is in the first Expand All, which is triggering the loading of elements into the tree.

If I use a breadth-first-search to contract (and reverse of that to expand), these operations are near instant _after_ the first load.  This approach minimizes UI updates by collapsing the top nodes first and expanding the top nodes last.

Maybe there is a way to load all the data inside the thread on the first expand. 🤔

**Comment by GICodeWarrior** [comment]
I've enabled UI Virtualization for the TreeView and implemented a few related performance improvements.

Please give it a try and let me know what you think.

**Comment by 4sval** [comment]
Wow, what a difference!
Thanks to virtualization, opening big folders, Go To, expand/collapse, is much faster now (makes sense lol).

Thanks for the investigation, I'll merge your PR and make a few modifications I have locally.

**Comment by GICodeWarrior** [comment]
Thanks.  I'm glad it's helpful.

The toughest part was figuring out that `ScrollViewer.CanContentScroll="True"` is needed.  This is a default in vanilla WPF, but Adonis UI leaves this out of their template, so it needs to be explicit here.  I didn't notice any documentation mentioning that this is required for TreeView virtualization, so it was a lot of debugging to solve that.

**Comment by 4sval** [comment]
It turns out that loading folders and packages took a big hit, it doubled the loading time on average, and Go To kind of broke when the folder is far from the virtualized tree area

I'm investigating

**Comment by GICodeWarrior** [comment]
Oh, that's not good.  I can take a look too if you can share a little more about how to reproduce these issues.

**Comment by 4sval** [comment]
Sure

---

- Go To
1. On whatever game you use, try to save a directory that is deep and far from the view of the root folder
2. Collapse all folders
3. Packages > Directories > yours > Go To
4. It is supposed to expand all parent folders and select the deeper one but since most of them are out of view, it gets stuck until you scroll closer to it
5. Furthermore, if you scroll up and down again, the scrolling gets laggy and sometimes teleports the selected folder into the view (if you bring [this](https://github.com/4sval/FModel/pull/372/files#diff-a3cdfb4ff0265b59cdc858da162ab06b8d463297b5a8da24d72ea9fd625bf781R259) back and scroll with your mouse from top to bottom and back fast enough, you can see those out-of-view folders getting opened again every time they are back into view)

---

- Folders Loading
1. Seems to be back to normal, not sure what happened

**Comment by GICodeWarrior** [comment]
Thanks.  I see the issue with Go To now.  I'll take a look.

**Comment by 4sval** [comment]
I will revert the changes related to folders because I can't find anything to fix it
Yield will still be used for everything package related

**Comment by GICodeWarrior** [comment]
Sorry I haven't gotten back to you.  I have an approach I've been chasing, but it's not fully working yet.  If/when I get that working, I'll post a new PR.

**Pull request merged**
