### PR TITLE
Fixed "Chapter 3 Season 5"

### PR DESCRIPTION
**Pull request by BriteBytes**

### CODE REVIEW

**Comment by 4sval** [comment]
I guess you didn't test your change

**Comment by BriteBytes** [comment]
My bad 🤦‍♂️ Only ever used GitHub for private stuff. Didn't mean to submit this pull request

**Comment by XTigerHyperX** [comment]
already fixed in the next commit , dw about it

**Comment by NotOfficer** [comment]
What even is that commit, this will produce the same output as before 🤨

**Pull request closed without merging**
